// declare typekit fonts
// @TODO: add to kit
$font-sans: sans-serif
$font-serifs: Georgia, serif

$font-museo-slab: museo-slab-1, museo-slab-2, $font-serifs
$font-proxima-nova: proxima-nova-1,proxima-nova-2, $font-sans
$font-proxima-nova-condensed: proxima-nova-condensed-1,proxima-nova-condensed-2, $font-sans
$font-futura-pt: futura-pt-1, futura-pt-2, $font-sans

$font-body: $font-museo-slab
$font-headline: $font-futura-pt
$font-logo: $font-proxima-nova , $font-headline
$font-mono: Consolas, Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif

// special use font stacks
// ampersands
$font-amp: GoudyBookletter1911Regular, Goudy Old Style, Baskerville, Palatino,  $font-serifs
// CAPS
$font_cap: $font-sans