<!-- Formalize (http://formalize.me) -->
<script src="js/libs/formalize/jquery.formalize.js"></script>

<!-- Lettering.js -->
<script src="js/libs/jquery.lettering.js"></script>

<!-- Geared Scrolling -->
<script src="js/libs/jquery.heyday.gearedscrolling.js"></script>

<!-- scripts concatenated and minified via ant build script-->
<script src="js/plugins.js"></script>
<script src="js/script.js"></script>
<!-- end concatenated and minified scripts-->