// SUSY
//**
//  Susy: Un-obtrusive grids for designers
//  By: Eric A. Meyer and OddBird
//  Site: susy.oddbird.net
//**
// Font Sizes --------------------------------------------------------------
$base-font-size: 14px !default
$base-line-height: $baseline
// Grid --------------------------------------------------------------
$total-cols: 6
$col-width: 140px
$gutter-width: $gutter
$side-gutter-width: $gutter_half


@import susy
// uncomment to output the full container width to the terminal
// @debug columns-width()