// --- Modular SCALE (used by _defaults.sass) -----------
// http://modularscale.com/
// This scale based on 14px (text) 140px (column width), musical fifth (2:3)
$ms-5: 5.463px
$ms-4: 6.222px
$ms-3: 8.194px
$ms-2: 9.333px
$ms-1: 12.291px
$ms0: 14px
$ms1: 18.436px 
$ms2: 21.000px
$ms3: 27.654px
$ms4: 31.500px
$ms5: 41.481px
$ms6: 47.250px
$ms7: 62.222px
$ms8: 70.875px
$ms9: 93.333px
$ms10: 106.313px
$base-font-size: $ms0